### ISSUE TITLE
Permission 'storage.objects.list' denied on resource

### ISSUE THREAD

**Issue by yikee** [zetaalphavector/inPars#13]
Hi! I am getting the error `AccessDeniedException: 403 xxx does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).` when I try to download the data using `gsutil cp gs://nm_datasets/trec_covid/runs/run.beir-v1.0.0-trec-covid-flat.trec $DATA`. Can you give us the access/any ideas on how to fix that? Thanks

**Comment by lhbonifacio** [comment]
Hi @yikee 
We[ just fixed](https://github.com/zetaalphavector/inPars/commit/2753ba4dc60fdc4d3e3346a6ace8be2189b5132d) this problem.
The url that was in this script was wrong and we corrected it to the right one.

**Comment by yikee** [comment]
it works, thanks!
