### ISSUE TITLE
Unsupervised Inpars model checkpoints?

### ISSUE THREAD

**Issue by ArvinZhuang** [zetaalphavector/InPars#23]
Hi, thanks for the open-sourced code, model checkpoints, and generated queries.
Im looking for the unsupervised inpars models checkpoints that are listed in Table 1 of https://dl.acm.org/doi/pdf/10.1145/3477495.3531863. But I could find them on huggingface hub. 
Could you have me with that? thanks!

**Comment by lhbonifacio** [comment]
Hi @ArvinZhuang 
Thanks for the interest in our work!

The models are available on HF hub: https://huggingface.co/zeta-alpha-ai

**Comment by ArvinZhuang** [comment]
Hi @lhbonifacio, seems all the available models are inpar-v2 which are all based on ms marco tuned monoT5? I'm actually interested in the inpar models that are not originally initialized with msmarco-tuned monoT5 (row 5 in the table)

**Comment by lhbonifacio** [comment]
Hi @ArvinZhuang.
We've upload the InPars-v1 models (from scratch) to our [HuggingFace repo](https://huggingface.co/zeta-alpha-ai).

**Comment by ArvinZhuang** [comment]
Hi @lhbonifacio, that's what I exactly want! thanks a lot!
