### ISSUE TITLE
Missing datasets library from the requirements.txt

### ISSUE THREAD

**Issue by stevaras2** [zetaalphavector/InPars#26]
I tried to train a model on my data, however, I received the following error
`Traceback (most recent call last):
  File "/opt/conda/envs/cross/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/cross/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/cross/lib/python3.10/site-packages/inpars/train.py", line 2, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'`

I fixed it by installing by myself the datasets library, but it would be great if it is installed when setting up the inpars library.

**Comment by lhbonifacio** [comment]
Hi @stevaras2 
Thank you for the interest in our work and for letting us know about this issue.
The library [was added to the requirement file](https://github.com/zetaalphavector/InPars/commit/6e32a2a29c726852c25b659fa9da6cd8e7e20459).
