### ISSUE TITLE
Could you please provide some examples?

### ISSUE THREAD

**Issue by WildLight** [zetaalphavector/inPars#6]
Hello, when I run the section "How to Generate" there need to add the parameter "bad_good, good_bad". Besides, the parameter "--collection" , can you give me some examples? Thanks you!
![image](https://user-images.githubusercontent.com/51358357/185825000-8e26978a-47ad-4acd-9d61-723f1eb9b241.png)

**Comment by lhbonifacio** [comment]
Hello @WildLight, thank you for your interest in our work!

We just corrected this "good bad" issue, the code should work fine now!
Regarding to the `--collection` example, we suggest you to look at the MS MARCO passages collection, [available here](https://msmarco.blob.core.windows.net/msmarcoranking/collection.tar.gz).
Briefly, the document collection to be used is a .tsv file formed by a `document_id` followed by the `document_text` (separated by a `\t`).

**Comment by WildLight** [comment]
Hello @lhbonifacio, thank a lot for your reply! :smile:

**Comment by rodrigonogueira4** [comment]
Hit @WildLight , I'm closing this but please reopen it if you still have any questions.
